[package]
name = "next-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["macros"] }
serde_json = { version = "1", features = ["raw_value"] }
# Documentation: https://docs.rs/vercel_runtime/latest/vercel_runtime
vercel_runtime = { version = "1.1.4" }
datafusion = { version = "49.0.0" }
datafusion-distributed = { git = "https://github.com/datafusion-contrib/datafusion-distributed", branch = "robtandy/move_chrono_to_main_dependencies" }
serde = { version = "1.0.203", features = ["derive"] }
futures = "0.3.31"
url = "2.5.7"
async-trait = "0.1.89"
tonic = "0.12.3"
tokio-stream = "0.1.17"
tower = "0.5.2"
hyper-util = "0.1.16"
arrow-flight = "55.2.0"

[dev-dependencies]
insta = "1.43.2"
tabled = "0.20.0"

# Each handler has to be specified as [[bin]]
[[bin]]
name = "sql"
path = "api/main.rs"
