[package]
name = "next-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["macros"] }
serde_json = { version = "1", features = ["raw_value"] }
# Documentation: https://docs.rs/vercel_runtime/latest/vercel_runtime
vercel_runtime = { version = "1.1.0" }
datafusion = { version = "39.0.0", default-features = false, features = [
    "array_expressions",
#    "crypto_expressions",
    "datetime_expressions",
    "encoding_expressions",
    "regex_expressions",
    "string_expressions",
    "unicode_expressions",
#    "compression",
#    "parquet",
] }
serde = { version = "1.0.203", features = ["derive"] }

# Each handler has to be specified as [[bin]]
[[bin]]
name = "sql"
path = "api/main.rs"
